// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ojcxclcveaccfstklurt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9qY3hjbGN2ZWFjY2ZzdGtsdXJ0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg3MDIyNTQsImV4cCI6MjA2NDI3ODI1NH0.PJR66rDWYuv9UGU5PoE37mcLX2NsPMYyrTaPymFlceM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});